### ISSUE TITLE
Group block excluding embedded question blocks from calculator and not exposing question answers to other form blocks with @

### ISSUE THREAD

**Issue by kenjikato** [quillforms/quillforms#144]
**Describe the bug**
I have a new Quill Form that I built that has a Group block with several Multiple Choice question input blocks (6 to be exact) each with 4 answers per Multiple Choice question blocks. I have tried several different ways to get the Calculator to work with these question blocks embedded within the Group block with no luck. I only ever get 0 as the calculated result.

If I implement a Multiple Choice question block outside of a Group block then things seem to calculate correctly. It’s only when a question block like the Multiple Choice question is embedded inside a Group block does it seem that the Calculator will not work properly.

I've also now discovered that any data input question block within a Group block does not expose the data input into those questions outside of the Group block itself.

For example, if I have a Name (Short Answer question block) and Telephone Number (Telephone question block) embedded in a Group block. The data entered in the Name and Telephone Number questions is never exposed outside of that Group block. The values entered into those questions can not be accessed on any other form step using the @ symbol.

**To Reproduce**
1. Create a new form.
2. Add in a Group block.
3. Add in a Short Text question block, Telephone question block, Multiple Choice question block, or any other question block to the Group block.
4. Add another form question step after the Group block step in the logical flow. 
5. Try to access any value from any question block embedded in the Group block using the @ symbol on the just created second form question step.
6. Try to calculate any value from any question block embedded in the Group block before moving to the second step in the overall form. 

**Expected behavior**
I would expect the data entered into any question block found within a Group block to be exposed for access outside the Group block using the @ symbol, or that the calculate option would process values from the question blocks found within the Group block.

**Desktop:**
 - OS: macOS Ventura 13.5.2
 - Browser: Safari 16.6, Firefox 117.0.1
 - WordPress version: 6.3.1
 - Quill Forms version: 3.2.2
 - Quill Forms Jump Logic and Calculator version: 3.5.0

**Comment by mdmag** [comment]
Hello @kenjikato,

Thanks for reaching out!
Let me investigate this and get back to you.

**Comment by mdmag** [comment]
@kenjikato 
I have tested the calculator itself and it worked fine.
Are you referring to "Points"?

**Comment by kenjikato** [comment]
@mdmag Yes part of the issue is getting the calculator to calculate points. I have not been able to make this work successfully when the calculation is using data from within a Group block.

But it is more than that. Any values entered into any type of form block that is embedded within a Group block are not accessible outside of the group block.

As I stated in the initial problem. Add in a simple multi choice block or shot answer block, and the values entered for those form blocks can not be accessed outside of the Group block.

Here's a link to a video I made to illustrate both issues.:
[Quill Forms Group Block Issue for Calculations and Accessing Values](https://kenjikato.com/media/Quill_Forms_02_Group_Block_Issue_01.mp4)

**Comment by mdmag** [comment]
Gotcha,

I will update logic addon soon to fix the points issue.
And for recalling information from group block, this will be fixed as well.

**Comment by mdmag** [comment]
Hello @kenjikato 

We have fixed both issues in version 3.2.3 
Please check and let me know.

**Comment by mdmag** [comment]
Closing due to no feedback but I can confirm that these issues have been fixed.

**Comment by kenjikato** [comment]
@mdmag I was finally able to test the fixes today.

✅ Working:  The @ icon will now properly reference values from blocks that are embedded within a Group block.

⚠️ Still not working: Calculations work sometimes but not always. It looks like there are issues with accessing variables for multiple different Multi Select blocks and other answers.

I'll create a video to show the multiple issues I'm now seeing.

I can also file another issue as there are new problems that have not appeared.

**Comment by mdmag** [comment]
I reopened the issue. You can send the video here please.

**Comment by mdmag** [comment]
Hello @kenjikato,

We have update logic addon to fix issues with the group block.
I will close this issue now and feel free to reopen it if you have the same issue.
